name: Multibranch

on:
  push:
    branches:
      - master
      - b
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Branch
      run: git branch --all

  update_b_branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/b'

    steps:
    - uses: actions/checkout@v3
    - name: Update B Branch
      run: |
        git checkout b
        git pull origin b
        
