name: Multibranch

on:
  push:
    branches:
      - master
      - a

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Check Branch
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/a' ]]; then
          echo "Updating 'b' branch. Add your custom steps here."
          # Add your custom steps for the 'b' branch here
        else
          echo "Updating branch other than 'b'. Add general steps here."
          # Add general steps for other branches here
        fi
