name: Multibranch

on:
  push:
    branches:
      - master
      - b
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Branch
      run: git branch --all
   
    - uses: actions/checkout@v3
    - name: Update B Branch
      run: |
        git checkout b
        git pull origin b
        
