name: Python application

on:
  push:
    branches: [ "b" ]
  pull_request:
    branches: [ "b" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Branch
      run: git branch --all
    
